### ISSUE TITLE
Unnecessary areItemStacksIdentical method

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CyclopsCore#100]
https://github.com/CyclopsMC/CyclopsCore/blob/1840463803c53bc2166effe6781274e5ad597003/src/main/java/org/cyclops/cyclopscore/helper/ItemStackHelpers.java#L183-L191

What's the point of this, specifically everything after the `&&` on line 190? I see no case when `ItemStack.areItemStacksEqual` would return true but this method would return false.

**Comment by rubensworks** [comment]
Either `ItemStack.areItemStacksEqual` used to not take into account stacksizes in the past, or I didn't check the implementation properly. Eitherway, the part after `&&` can indeed be removed.

**Comment by josephcsible** [comment]
Can the entire method be deprecated for removal in 1.13?

**Comment by rubensworks** [comment]
Yep, good idea.
