### ISSUE TITLE
Crash when placing Integraded Dynamic Variable Card into The Betweenlands Weedwood Crafting Table

### ISSUE THREAD

**Issue by Jandakast** [CyclopsMC/CyclopsCore#111]
#### Issue type:

- :bug: Bug

____

#### Short description:
Crash when attempting to render the Variable Card from Integrated Dynamics in the Weedwood Crafting Bench from The Betwenlands.

Originally reported in SevTech Ages but can be reproduced with just The Betweenlands and Integrated Dynamics installed. DarkPacks/SevTech-Ages#2596

Was directed here from The Betweenlands dev. 
https://github.com/Angry-Pixel/The-Betweenlands/issues/618

#### Steps to reproduce the problem:
1. Place Weedwood Crafting table
2. Place Integrated Dynamics Variable Card into table
3. Enjoy the crash

#### Expected behaviour:
Not to crash

____

#### Versions:
Common Capabilities 1.4.0
Cyclops Core 0.11.6
Integrated Dynamics 0.11.12
JEI 4.9.1.189
Forge 2702

#### Log file:
https://gist.github.com/Jandakast/665826264ddb5378ad1e815d2f98d3d0

**Comment by rubensworks** [comment]
Looks like this has been fixed in betweenlands already. Not something that was incorrect on our end.
