### ISSUE TITLE
Client Crash when rendering fluids in entangled chalices

### ISSUE THREAD

**Issue by belathus** [CyclopsMC/CyclopsCore#112]
#### Issue type:

- :bug: Bug

____

#### Short description:
I was sitting in my base looking up fuels in JEI when the screen turned a solid light-blue color. It paused for a while, then crashed. I restarted MC, and was able to join the server for a while, until it crashed again.

For reference, I have 2 pairs of entangled chalices being used, and they've been in use for more than a week now. One transports blood, and the other transports liquid XP. Both fluids are being generated by the same mob farm, which uses spiked plates and sanguinary altars to generate blood, and an EIO XP vacuum to collect the XP.

#### Steps to reproduce the problem:
1. build mob farm
2. set farm to collect blood and XP
3. transport XP and blood to base using entangled chalices
4. let run for probably a rather long period of time when suddenly it crashes.

#### Expected behaviour:
I generally expect Minecraft not to crash.

____

#### Versions:
- This mod: 0.11.6
- Minecraft: 1.12.2
- Forge: 14.23.3.2691

#### Log file:
https://paste.dimdev.org/cofegelayo.txt

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/EvilCraft/commit/5b7fd6df04227b99930715df5effdc095c99c17a
