### ISSUE TITLE
Crash while entering a dimension

### ISSUE THREAD

**Issue by Davoleo** [CyclopsMC/CyclopsCore#114]
#### Issue type:

- :bug: Bug

____

#### Short description:
This happened to me while I was returning to the overworld from another mod's dimension

#### Steps to reproduce the problem:

1. enter a custom mod dimension or vanilla dimensions

#### Expected behaviour:

I didn't expect a crash

____

#### Versions:

- This mod: 0.11.8
- Minecraft: 1.12.2
- Forge: 2745

#### Log file:

Crash report: https://paste.dimdev.org/sazurogini.mccrash
latest log file: https://pastebin.com/GwXbfrW8

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
