### ISSUE TITLE
Crash w/ Everlasting Abilities Ability Bottle GUI

### ISSUE THREAD

**Issue by HyperMan19680** [CyclopsMC/CyclopsCore#117]
#### Issue type:

- :bug: Bug

____

#### Short description:

Crashed when I tried to open an ability bottle from Everlasting Abilities.

#### Steps to reproduce the problem:

1. Download the mod versions below.
2. Open an Ability Bottle.

#### Expected behaviour:
The GUI Should have opened up with no issues reported by VanillaFix.

____

#### Versions:

- This mod: 0.11.10
- Everlasting Abilities:1.12.2-1.3.18
- Minecraft: 1.12.2 
- Forge: 14.23.4.2759

#### Log file:

https://paste.dimdev.org/wezebavoto.mccrash

**Comment by rubensworks** [comment]
Can you reproduce it consistently?

Can you reproduce it without any other mods installed?
