### ISSUE TITLE
Remove sidedInventoryHandlers?

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CyclopsCore#122]
https://github.com/CyclopsMC/CyclopsCore/blob/b92868af856101113b26206253cfa903aa50bae3/src/main/java/org/cyclops/cyclopscore/tileentity/InventoryTileEntityBase.java#L30-L34

There seems to be no code in any repository in the CyclopsMC organization that uses sidedInventoryHandlers for anything. Lines 30 and 34 above seem to be the only places it occurs at all. Any reason to not just remove it?

**Comment by rubensworks** [comment]
Hmm, indeed, it looks like that can be removed. Probably some leftover code from a refactor at some point.
