### ISSUE TITLE
cyclopscore{0.5.3} crashes client on startup

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/CyclopsCore#13]
fml latest log: http://paste.ee/p/cvwCi

Crash report: http://paste.ee/p/d8Wqx

**Comment by rubensworks** [comment]
1.9 is in a state of flux atm: https://twitter.com/LexManos/status/713081449994276865?s=09
An earlier Forge release (like 1767) will work just fine.
I'll make a new release once Forge stabilizes a bit.

**Comment by rubensworks** [comment]
Fixed in b0df023adf291016e79a282a4ffe2c4d5c333547, release coming soon.
