### ISSUE TITLE
Cyclops NullPointException Error on Cyclops v1.0.3 with MC v1.12.2

### ISSUE THREAD

**Issue by SirTwsted** [CyclopsMC/CyclopsCore#131]
#### Issue type:

- :bug: Bug
Crash upon loading minecraft v1.12.2 with Cyclops v1.0.3
____

#### Steps to reproduce the problem:

1. ...install Cyclops v1.0.3
2. ...load minecraft v1.12.2

#### Expected behaviour:

I expected the mod to work properly without crashing.
____

#### Versions:

- This mod: v1.0.3
- Minecraft: 1.12.2
- Forge: v14.23.5.2768

#### Log file:

https://hastebin.com/ohopajolut.http

**Comment by rubensworks** [comment]
You have to update commoncapabilities to the latest version.

**Comment by SirTwsted** [comment]
aah ok thank you.  I wish that info was on the Cyclops info page.
again, thank you and sorry for the hassles :)

**Comment by SirTwsted** [comment]
Update 10 minutes later.  I upgraded commoncapabilities mod to the latest version for MC-v1.12.2
and I got this error back when loading MC --> https://hastebin.com/opodorazog.http
When upgrading from CyclopsCore-1.12.2-0.11.10.jar
which doesnt give me a problem, only the updated version does.

<blockquote><div><strong><a href="https://hastebin.com/opodorazog.http">hastebin</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Same problem, you are using outdated mods, integrateddynamics in this case.

Please make sure you're using the latest version of mods before reporting stuff.

**Comment by SirTwsted** [comment]
is there a list of all the mods that cyclops are associated with. so I can update all of them at the same time.?
This domino effect is killing me...lol

**Comment by rubensworks** [comment]
https://minecraft.curseforge.com/projects/cyclops-core/relations/dependents?filter-related-dependents=3

<blockquote><img src="https://media.forgecdn.net/avatars/0/93/635227964539626926.png" width="48" align="right"><div><strong><a href="https://minecraft.curseforge.com/projects/cyclops-core/relations/dependents?filter-related-dependents=3">Related Dependents - Cyclops Core - Mods - Projects - Minecraft CurseForge</a></strong></div></blockquote>

**Comment by SirTwsted** [comment]
Thank you. Ive been away from Minecraft for a long while, because of work and studying.
so im trying to play catch up.  pls bare with me, Thank you for being very patient. :)
