### ISSUE TITLE
Crashing with latest build 1.12.2-1.1.0

### ISSUE THREAD

**Issue by raltus** [CyclopsMC/CyclopsCore#134]
#### Issue type:

- :bug: Bug

____

#### Short description:
Latest build causes a error with EvilCraft.

#### Steps to reproduce the problem:

1. Load Minecraft with the latest Cyclops Core 1.12.2-1.1.0 and EvilCraft 1.12.2-0.10.70

#### Expected behaviour:
Everything loads fine with the previous version installed. Once the new version is installed everything loads fine until it gets to EvilCraft. I updated to the latest Forge build after the first time in case that was the issue, first crash was with .2815. 

____

#### Versions:

- This mod: 1.12.2-1.1.0
- Minecraft: 1.1.2.
- Forge: 14.23.5.2821

#### Log file:

https://gist.github.com/raltus/dc1763502150207f0bd5f56a18ede0dd

**Comment by rubensworks** [comment]
CurseForge is having some issues that caused some of my mod updates to be rejected: https://twitter.com/CurseForge/status/1108183445442707456

Please wait to update until that is resolved, or you can use the dev builds (see README).

<blockquote><img src="https://pbs.twimg.com/profile_images/725406699369058304/0mVMpCrb_400x400.jpg" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/CurseForge/status/1108183445442707456">CurseForge on Twitter</a></strong></div><div>“Attention Authors,

We are currently working through an issue with our upload service. This is causing uploads to be rejected with a message to contact support. Please hold tight and reach out to support while we work on the fix.

Thanks,
The CurseForge Team”</div></blockquote>

**Comment by rubensworks** [comment]
FYI, I've managed to update the missing mods again on CurseForge, everything should be in order now!
