### ISSUE TITLE
Handle invalid recipe files more gracefully

### ISSUE THREAD

**Issue by benserwa** [CyclopsMC/CyclopsCore#135]
#### Issue type:

- :bug: Bug

____

#### Short description:

My modpack crashes with most recent version of Cyclops Core.

#### Versions:

- This mod: 1.1.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2831

#### Log file:

https://paste.dimdev.org/jenixokike.mccrash

**Comment by benserwa** [comment]
Just for a try I updated Forge and it still crashes.

https://paste.dimdev.org/damitoboje.mccrash

<blockquote><div><strong><a href="https://paste.dimdev.org/damitoboje.mccrash">hastebin</a></strong></div></blockquote>

**Comment by benserwa** [comment]
Never mind, I had an invalid XML file in the Integrated Dynamics config folder. Duh. Probably that should fail more gracefully if possible?

**Comment by rubensworks** [comment]
Indeed, that can be improved.
