### ISSUE TITLE
Important Users lookup cost a long time in server thread

### ISSUE THREAD

**Issue by SeraphJACK** [CyclopsMC/CyclopsCore#139]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I tried to start a server with this mod, it stucked and thread dump shows that CyclopsCore is blocking the main thread due to network IO.

#### Steps to reproduce the problem:

1. Start the game with this mod.

#### Expected behavior:

Do it off main thread.

____

#### Notes

[Seems you tried to do it off main thread](https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/src/main/java/org/cyclops/cyclopscore/tracking/ImportantUsers.java#L54), but you may use `Thread::start` instead of `Thread::run`, which is simply calling that Runnable in main thread.

**Comment by rubensworks** [comment]
Oh, my bad...
