### ISSUE TITLE
Not a valid mod.

### ISSUE THREAD

**Issue by Matthew021750** [CyclopsMC/CyclopsCore#140]
#### Issue type: Not recognised as a mod

- :bug: Bug CyclopsCore is not a valid mod file (CyclopsCore-1.14.4-1.5.4-sources.jar)

____

#### Short description:

Minecraft 1.14.4 does not register 1.5.4 as a valid mod when installed to mods folder, stated as "not installed". Under warning, MC states that it's not a valid mod file.

#### Steps to reproduce the problem:

Download Colossal-Chests-Mod-1.14.4.jar and use minecraft version 1.14.4 then the game would not register CyclopsCore as a valid mod file. put the Colossal Chests mod into mod folder in .minecraft

#### Expected behaviour:

Can't enter game as CyclopsCore is "not installed" and in warning log says that CyclopsCore is "not a valid mod file".

____

#### Versions:

- This mod: 1.5.4
- Minecraft: 1.14.4
- Forge: 28.1.26

#### Log file:

https://pastebin.com/xLUj7pJ2

**Comment by rubensworks** [comment]
You are using the sources file (`CyclopsCore-1.14.4-1.5.4-sources.jar`), which is the wrong one.

You should be using `CyclopsCore-1.14.4-1.5.4.jar`.
