### ISSUE TITLE
EvilCraft: crash on server

### ISSUE THREAD

**Issue by Coloryr** [CyclopsMC/CyclopsCore#141]
#### Issue type:

- :bug: Bug

#### Versions:

- This mod: CyclopsCore-1.12.2-1.6.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847

and 
EvilCraft: 1.12.2-0.10.78

#### Log file:

crash report:
https://paste.ubuntu.com/p/6dgB6ZhfMg/

**Comment by rubensworks** [comment]
Please include steps to reproduce this problem.

**Comment by Coloryr** [comment]
I don't konw my player do some things in my server,just starting server,and it crashing.
