### ISSUE TITLE
[1.12.2] java.lang.NullPointerException on Colossal Chest placement

### ISSUE THREAD

**Issue by MusicMaestro123** [CyclopsMC/CyclopsCore#142]
#### Issue type:

- :bug: Crash

____

#### Short description:

It crashed when I placed the final block of the colossal chest.

#### Steps to reproduce the problem:

1. Download listed mods in crash report.
2. Construct obsidian colossal chest.
3. It will say: Shutting down internal server.

#### Expected behaviour:

The chest to assemble and for it to not crash.

____

#### Versions:

- This mod: 1.12.2-1.6.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file/Crash report:

[Click to view crash report on pastebin!](https://pastebin.com/KrPYxu9S)

**Comment by rubensworks** [comment]
Thanks for reporting!
