### ISSUE TITLE
Cyclops Core pauses during forge startup for 45 seconds when playing offline

### ISSUE THREAD

**Issue by Demolishun** [CyclopsMC/CyclopsCore#143]
#### Issue type:

- :bug: Bug/Undesired Behavior 

____

#### Short description:

I often play the game without internet.  So that means I play offline.  On game startup during the Forge loading screen Cylcops Core pauses the startup for 45 seconds.  I can actually hear the cpu fan slow down during this time.  This tells me it is waiting for an event.  

#### Steps to reproduce the problem:

1. Add CyclopsCore-1.12.2-1.6.3.jar to a modpack.
2. Load initially with internet to get everything working properly.
3. Turn off CyclopsCore analytics and version check in config.  (I suspected it was network related)
4. Startup in offline mode.
5. Notice that is phase 4 of 7 (4/7) of the Forge startup screen CyclopsCore pauses for approximately 45 seconds.

#### Expected behaviour:

I was expecting Cyclops Core to startup more quickly than this.
____

#### Versions:

- This mod: CyclopsCore-1.12.2-1.6.3
- Minecraft: 1.12.2 
- Forge: FTB Academy Modpack

**Comment by rubensworks** [comment]
Hmm, I thought this was fixed already. 
Thanks for reporting!

Note to self: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.12/src/main/java/org/cyclops/cyclopscore/tracking/Versions.java#L101

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>
