### ISSUE TITLE
Allow escaping " (double quotes) in NBT Path

### ISSUE THREAD

**Issue by SCLeoX** [CyclopsMC/CyclopsCore#145]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I don't think it is currently possible to match keys with double quotes in them. It would be nice to allow escaping double quotes: `["a\"b"]`.

The downside of this is that now back slashes need escaping as well. So an alternative might be escaping double quotes by another double quotes: `["a""b"]`.

I can make a PR for this, if you think it will be a decent feature.

**Comment by rubensworks** [comment]
The slash-based escaping sounds like a good idea!
Feel free to make a PR for it.

Be sure to add some unit tests for this, I aim to have a 100% test coverage of NBT Path :-)
