### ISSUE TITLE
[Crash] [1.12.2]  Crash on picking up an unknown item

### ISSUE THREAD

**Issue by AlienXtream** [CyclopsMC/CyclopsCore#147]
#### Issue type:

- :bug: Bug 

____

#### Short description:

crash on picking up an unknown elder guardian drop (it crashes on pickup so i cant see it)

its too late at night for me to do more testing myself to determine exactly WHAT item is the problem (100% another mods item as it does NOT happen with just cyclops core). i will do more testing to determine exactly WHAT item and make a report on their end too but for now if there happens to be a band-aid solution you can implement on your side and its not too much trouble.
sorry about the inconvenience of having to look at an older version after updating :(
#### Steps to reproduce the problem:

1. kill a guardian and collect its drops (loot table added onto by unknown mod. will not crash with JUST cyclops core. more info will be provided soon. again, sorry :( )

#### Expected behaviour:

____

#### Versions:

- This mod: 1.6.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

#### Log file:
https://pastebin.com/URDRMVHL

**Comment by AlienXtream** [comment]
oh hey, the bug report has a little caterpillar icon :D

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by AlienXtream** [comment]
wow.. that was FAST...

**Comment by AlienXtream** [comment]
its air... its a damn air block.... and it crashes whenever it renders the mouse over...
