### ISSUE TITLE
Crash when placing water in the world

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/CyclopsCore#15]
https://yadi.sk/d/wyIv9nzUrFChm
Source: http://minecraft.curseforge.com/projects/cyclops-core?comment=5

**Comment by LlubNek** [comment]
Probably related:  I had a crash when picking up lava.
I'm using CyclopsCore-1.9-0.5.6.jar on Forge 1.9-12.16.0.1865.

Here's the log and crash report:
[crash-2016-04-26_05.36.54-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/236303/crash-2016-04-26_05.36.54-client.txt)
[fml-client-latest.log.txt](https://github.com/CyclopsMC/CyclopsCore/files/236305/fml-client-latest.log.txt)
[latest.log.txt](https://github.com/CyclopsMC/CyclopsCore/files/236306/latest.log.txt)

**Comment by rubensworks** [comment]
Thanks @LlubNek! These logs will definitely help :)
