### ISSUE TITLE
Server Crash - Null Pointer Exception due to race condition

### ISSUE THREAD

**Issue by Yourname942** [CyclopsMC/CyclopsCore#152]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The server crashed on booting up.

#### Steps to reproduce the problem:

1. launch the server
2. experience crash

#### Expected behaviour:

The server should boot up with no issues

____

#### Versions:

- This mod: 1.16.4-1.11.1
- Minecraft: 1.16.5
- Forge: 36.0.22

#### Log file:
Crash Log:
https://gist.github.com/Yourname942/2f2dbfe709e2971a096ead6bed776d47
Latest Log:
https://gist.github.com/Yourname942/75a097d5378e41581c1f4f02a366cb75

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
@Yourname942 Does this crash always happen, or just sometimes? Does this only occur for you when other mods are installed?

Note to self: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.16/src/main/java/org/cyclops/cyclopscore/infobook/InfoBookRegistry.java#L83

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by Yourname942** [comment]
This is the first time it has happend, so I'm not sure how frequently it would occur

**Comment by rubensworks** [comment]
Ok, good to know, so probably a race condition.

**Comment by rubensworks** [comment]
Haven't been able to reproduce this, but next version will contain a change that will make it easier to debug if it should occur again.

**Comment by rubensworks** [comment]
Closing this in the meantime. Please comment (with logs) should this issue occur again for anyone.
