### ISSUE TITLE
Server Crash NullPointerException

### ISSUE THREAD

**Issue by Yourname942** [CyclopsMC/CyclopsCore#157]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The server crashes sometime during the booting up of the server. It may be related to this: https://www.curseforge.com/minecraft/mc-mods/illagers/issues/2

#### Steps to reproduce the problem:

1. Encounter in-game crash ( https://www.curseforge.com/minecraft/mc-mods/illagers/issues/2 )
2. Boot up server again
3. crash
4. repeat steps 2-3

#### Expected behaviour:

I expect there to be no issues with org.cyclops.cyclopscore.infobook.InfoBookRegistry.afterRecipesAndTagsLoaded
____

#### Versions:

- This mod: 1.16.5-1.11.5
- Minecraft: 1.16.5
- Forge: 1.6.2

#### Log file:
crash log: 
https://gist.github.com/Yourname942/0a9bd6bca8154e469c461fe4ff6dd56b
latest log:
https://gist.github.com/Yourname942/82fac4448fe6cd753387fd8f310378d7
debug log:
https://gist.github.com/Yourname942/93662a5efd3afd1e914198547182a40f

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Related to #152
