### ISSUE TITLE
Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by CanBoy67** [CyclopsMC/CyclopsCore#158]
#### Issue type:

- :bug: Bug 

____

#### Short description:
During loading minecraft crashes with a java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid. I'm not sure if your still mantaining the 1.15.2 version of this mod or not but the above error is preventing me from playing the custom pack i'm making with this 

#### Steps to reproduce the problem:

1. Load Game
2. Wait 
3. Game Crashes with above error

#### Expected behaviour:
Loading to the main menu with no issue

____

#### Versions:

- This mod: 1.15.2-1.9.0
- Minecraft: 1.15.2
- Forge: 31.2.47

#### Log file:
Crash Log: https://pastebin.com/XbZ9v78t

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm sorry, but 1.15 is not being maintained anymore.
