### ISSUE TITLE
Dedicated server crash on startup. (after/during world load)

### ISSUE THREAD

**Issue by CharlieUniformNovemberTango** [CyclopsMC/CyclopsCore#159]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Dedicated server crash. Possible conflict with agricraft.

#### Steps to reproduce the problem:

1: Launch dedicated server with mods as described below.
2: Wait for crash at the end of world build.

#### Expected behaviour:

No crash ¯\_(ツ)_/¯
____

#### Versions:

- This mod: CyclopsCore-1.16.5-1.11.7
- Minecraft: 1.16.5
- Forge: 36.1.30
- CommonCapabilities-1.16.5-2.7.0
-IntegratedCrafting-1.16.5-1.0.15
-IntegratedDynamics-1.16.5-1.8.4
-IntegratedTerminals-1.16.5-1.2.4
-IntegratedTunnels-1.16.5-1.8.1
          
                Complete mod pack (custom)
-AdditionalEnchantedMiner-1.16.5-16.1.7.jar                         
-AdLods-1.16.4-4.1.6.0-build.0130.jar                               
-AdvancedRocketry-1.16.5-2.0.0-12-universal.jar                     
-ae2extras-1.3-1.16.5.jar                                           
-agricraft-3.0.2.jar                                                
-alltheores-1.3.2-1.16.5-36.1.0.jar                                 
-AppleSkin-mc1.16.2-forge-1.0.14.jar                                
-appliedenergistics2-8.4.0.jar                                      
-archers_paradox-1.16.4-1.2.0.jar                                   
-architectury-1.17.22-forge.jar                                     
-AutoRegLib-1.6-49.jar                                              
-BetterAdvancements-1.16.5-0.1.0.108.jar                            
-BetterMineshafts-Forge-1.16.4-2.0.4.jar                            
-biggerreactors-1.16.4-0.4.3.jar                                    
-BiomesOPlenty-1.16.5-13.1.0.471-universal.jar                      
-Bookshelf-1.16.5-10.1.11.jar                                       
-Botania-1.16.5-416.jar                                             
-buildinggadgets-1.16.5-3.8.0.jar                                   
-chiseled0.4.3.jar                                                  
-chiselsandbits-0.3.4-RELEASE.jar                                   
-citadel-1.7.1-1.16.5.jar                                           
-ClientTweaks_1.16.3-5.3.0.jar                                      
-Clumps-6.0.0.25.jar                                                
-CodeChickenLib-1.16.4-3.5.1.408-universal.jar                      
-cofh_core-1.16.4-1.2.1.jar                                         
-comforts-forge-1.16.5-4.0.0.4.jar                                  
-compactstorage-1.16.5-5.1b17.jar                                   
-constructionwand-1.16.5-2.2.jar                                    
-Controlling-7.0.0.23.jar                                           
-CookingForBlockheads_1.16.5-9.3.2.jar                              
-CraftingTweaks_1.16.5-12.2.1.jar                                   
-CraftTweaker-1.16.5-7.1.0.314.jar                                  
-create-mc1.16.5_v0.3.1c.jar                                        
-CTM-MC1.16.1-1.1.2.6.jar                                           
-Cucumber-1.16.4-4.1.10.jar                                         
-curios-forge-1.16.5-4.0.5.2.jar                                    
-Cyclic-1.16.5-1.2.11.jar                                           
-DarkUtilities-1.16.5-8.0.10.jar                                    
-DefaultOptions_1.16.5-12.2.1.jar                                   
-DungeonCrawl-1.16.3-2.2.4.jar                                      
-elevatorid-1.16.5-1.7.13.jar                                       
-EnchantmentDescriptions-1.16.5-7.0.8.jar                           
-enderchests-1.16-1.7.7.jar                                         
-EnderStorage-1.16.4-2.7.1.166-universal.jar                        
-envirocore-1.16.5-3.0.8.0.jar                                      
-envirotech-1.16.5-3.0.8.0.jar                                      
-ExCompressum_1.16.5-4.0.3.jar                                      
-FarmingForBlockheads_1.16.5-7.3.1.jar                              
-FastFurnace-1.16.4-4.4.0.jar                                       
-FastLeafDecay-v25.jar                                              
-FastWorkbench-1.16.4-4.5.1.jar                                     
-filenames.txt                                                      
-ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar                       
-ftb-backups-2.1.1.6.jar                                            
-ftb-chunks-1605.2.3-build.75.jar                                   
-ftb-gui-library-1605.2.1.41-forge.jar                              
-gates-1.7.1.jar                                                    
-gravestone-1.16.5-1.0.4.jar                                        
-Hwyla-forge-1.10.11-B78_1.16.2.jar                                 
-iceandfire-2.1.7-1.16.5.jar                                        
-ImmersiveEngineering-1.16.5-5.0.0-135.jar                          
-ImmersivePetroleum-1.16.5-3.3.0-4.jar                              
-Industrial Agriculture[Core]-1.16.5-1.7.1.jar                      
-industrial-foregoing-1.16.5-3.2.13.1-5.jar                         
-Infinitylib-2.0.4.jar                                              
-ironchest-1.16.4-11.2.10.jar                                       
-IronJetpacks-1.16.4-4.2.0.jar                                      
-item-filters-1605.2.4-build.30-forge.jar                           
-jei-1.16.5-7.7.0.106.jar                                           
-jeiintegration_1.16.5-7.0.1.15.jar                                 
-JEITweaker-1.16.5-1.0.1.31.jar                                     
-journeymap-1.16.5-5.7.1.jar                                        
-JustEnoughResources-1.16.5-0.12.1.119.jar                          
-LibVulpes-1.16.5-1.0.2-25-universal.jar                            
-Lollipop-1.16.5-3.2.9.jar                                          
-Mantle-1.16.5-1.6.109.jar                                         
-mcjtylib-1.16-5.0.19.jar                                           
-Mekanism-1.16.5-10.0.21.448.jar                                    
-MekanismGenerators-1.16.5-10.0.21.448.jar                          
-MekanismTools-1.16.5-10.0.21.448.jar                               
-mgui-1.16.5-3.2.0.jar                                              
-mobcatcher-3.2.jar                                                 
-mob_grinding_utils-1.16.5-0.4.22.jar                               
-morered-1.16.5-2.1.0.3.jar                                         
-Morpheus-1.16.5-4.2.70.jar                                         
-MouseTweaks-2.14-mc1.16.2.jar                                      
-MysticalAgradditions-1.16.4-4.1.5.jar                              
-MysticalAgriculture-1.16.4-4.1.8.jar                               
-MysticalCustomization-1.16.4-2.1.4.jar                             
-NaturesCompass-1.16.5-1.8.6.jar                                    
-Neat 1.7-27.jar                                                    
-OreExcavation-1.8.157.jar                                          
-pamhc2crops-1.16.3-1.0.2.jar                                       
-pamhc2foodcore-1.16.3-1.0.2.jar                                    
-pamhc2foodextended-1.16.3-1.0.2.jar                                
-pamhc2trees-1.16.3-1.0.1.jar                                       
-Patchouli-1.16.4-51.jar                                            
-phosphophyllite-1.16.4-0.4.5.jar                                   
-Placebo-1.16.4-4.5.0.jar                                           
-pneumaticcraft-repressurized-1.16.5-2.12.5-190.jar                 
-polymorph-forge-1.16.5-0.25.jar                                    
-Powah-1.16.5-2.3.16.jar                                            
-ProjectE-1.16.5-PE1.0.1B.jar                                       
-Quark-r2.4-312.jar                                                 
-randompatches-2.4.4-forge.jar                                      
-ReAuth-1.16-Forge-3.9.3.jar                                        
-redlogic-1.16.4-1.0.0.jar                                          
-RedstoneExtras-1.16.2-1.0.0.8.jar                                  
-refinedpipes-0.5.jar                                               
-refinedstorage-1.9.13.jar                                          
-rftoolsbase-1.16-2.0.10.jar                                        
-Runelic-1.16.5-7.0.1.jar                                           
-ScalableCatsForce-2.13.5-build-2-with-library.jar                  
-shetiphiancore-1.16-3.8.5.jar                                      
-SoundFilters-0.14_for_1.16.2.jar                                   
-spark-forge.jar                                                    
-StorageDrawers-1.16.3-8.2.2.jar                                    
-swingthroughgrass-1.16.4-1.5.3.jar                                 
-TConstruct-1.16.5-3.0.4.197.jar                                    
-tetra-1.16.5-3.12.0.jar                                            
-thermal_cultivation-1.16.4-1.2.0.jar                               
-thermal_expansion-1.16.4-1.2.0.jar                                 
-thermal_foundation-1.16.4-1.2.0.jar                                
-thermal_innovation-1.16.4-1.2.0.jar                                
-thermal_locomotion-1.16.4-1.2.0.jar                                
-tinyredstone-1.16.5-1.8.3.jar                                      
-titanium-1.16.5-3.2.8.4-10.jar                                     
-Toast-Control-1.16.4-4.3.1.jar                                     
-torchmaster-2.3.7.jar                                              
-Transport-1.16.5-3.6.0.jar                                         
-twilightforest-1.16.5-4.0.490-universal.jar                        
-useful_backpacks-1.16.5-1.12.1.90.jar                              
-u_team_core-1.16.5-3.2.1.196.jar                                   
-valkyrielib-1.16.5-3.0.8.0.jar                                     
-WailaHarvestability-mc1.16.x-forge-1.1.15.jar                      
-WaterStrainer-1.16.3-10.0.0.jar                                    
-WAWLA-1.16.5-8.0.1.jar                                             
-Waystones_1.16.5-7.6.2.jar                                         
-xnet-1.16-3.0.13.jar                                               
-XNetGases-1.16.5-2.2.6.jar                                         
-YungsApi-1.16.4-Forge-6.jar                                        

#### Log file:
[debug-1.log](https://github.com/CyclopsMC/CyclopsCore/files/6682059/debug-1.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by InfinityRaider** [comment]
For reference: https://github.com/AgriCraft/AgriCraft/issues/1356
If you figure out what is causing this, and if my code is somehow responsible, that is the place to come yell at me.

**Comment by rubensworks** [comment]
@InfinityRaider It looks like this is a problem on your end:
```
java.lang.ClassCastException: class org.cyclops.integrateddynamics.core.network.Network cannot be cast to class net.minecraftforge.common.capabilities.ICapabilityProvider (org.cyclops.integrateddynamics.core.network.Network and net.minecraftforge.common.capabilities.ICapabilityProvider are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @7668892a)
	at com.infinityraider.infinitylib.capability.CapabilityHandler.addCapabilities(CapabilityHandler.java:51)
	at com.infinityraider.infinitylib.capability.CapabilityHandler.addCapabilitiesRaw(CapabilityHandler.java:63)
	at net.minecraftforge.eventbus.ASMEventHandler_114_CapabilityHandler_addCapabilitiesRaw_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at org.cyclops.integrateddynamics.core.network.Network.gatherCapabilities(Network.java:120)
	at org.cyclops.integrateddynamics.core.network.Network.<init>(Network.java:98)
```

The `T` inside `AttachCapabilitiesEvent` is not guaranteed to be a `ICapabilityProvider`.
I also suspect you may be missing a more specific type for `T` in your event subscriber, as you probably don't want to be listening to capabilities for networks of this mod?

In any case, let me know if there's anything I can do to help! :-)
Closing this in the meantime.

**Comment by InfinityRaider** [comment]
Not sure if this is the same thing though.
The Capability cast issue was fixed in a [recent InfinityLib commit ](https://github.com/InfinityRaider/InfinityLib/commit/32c0ce06eaaeb9419cd343dadd0ed4215479ad26), as I was, indeed, too overzealously casting the object to ICapabilityProvider.

The stacktrace of this issue though is different and does not hint to InfinityLib at all:

```
java.lang.RuntimeException: Error in fromNBT for field element. Error: null
	at org.cyclops.cyclopscore.persist.nbt.INBTSerializable$SelfNBTClassType.readPersistedField(INBTSerializable.java:79) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.INBTSerializable$SelfNBTClassType.readPersistedField(INBTSerializable.java:36) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTClassType$CollectionNBTClassType.readPersistedField(NBTClassType.java:730) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTClassType$CollectionNBTClassType.readPersistedField(NBTClassType.java:684) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTClassType.persistedFieldAction(NBTClassType.java:664) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTClassType.performActionForField(NBTClassType.java:623) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.readPersistedField(NBTProviderComponent.java:40) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.nbt.NBTProviderComponent.readGeneratedFieldsFromNBT(NBTProviderComponent.java:53) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.world.WorldStorage.readGeneratedFieldsFromNBT(WorldStorage.java:24) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.world.WorldStorage.readFromNBT(WorldStorage.java:36) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.world.WorldStorage.initDataHolder(WorldStorage.java:88) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.world.WorldStorage.loadData(WorldStorage.java:96) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.persist.world.WorldStorage.onStartedEvent(WorldStorage.java:66) ~[cyclopscore:1.11.7]
	at org.cyclops.cyclopscore.init.ModBase.onServerStarted(ModBase.java:316) ~[cyclopscore:1.11.7]
	at org.cyclops.integrateddynamics.IntegratedDynamics.onServerStarted(IntegratedDynamics.java:195) ~[integrateddynamics:1.8.4]
	at net.minecraftforge.eventbus.ASMEventHandler_6_ModBase_onServerStarted_FMLServerStartedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:106) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
```

**Comment by rubensworks** [comment]
I think it is the same thing though. This error is preceded by a print of the invocation target exception, which is a `ClassCastException`. But for some reason, that stacktrace is incomplete, while the one from the other linked issue is.

**Comment by InfinityRaider** [comment]
I see, I shall push a release shortly and ask for feedback.
