### ISSUE TITLE
NoClassDefFoundError: org/cyclops/integrateddynamics/tileentity/TileCoalGenerator

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/CyclopsCore#16]
the Game crashes on startup 
crash log: http://paste.ee/p/tmWqS
I use the newest Versions. 
regards jokish

**Comment by rubensworks** [comment]
Thanks, I'll look into it right away.

**Comment by rubensworks** [comment]
This has been fixed in CyclopsMC/IntegratedDynamics@a38b943cdda9db8a74a8aa05d5b23e9f1bd7e71a
I'll prepare a new release.
