### ISSUE TITLE
Server crash when a player goes to a Dungeon Dimensions

### ISSUE THREAD

**Issue by AerWyn81** [CyclopsMC/CyclopsCore#162]
Hi, 

I don't know if it's your mod that is responsible, but in the stacktrace it is displayed.
If you think it's not your responsibility, I would go to the developer of the other mod!

#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

The server crashes when a player goes to a [Dungeon Dimension](https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons)
Maybe a compatibility issue.
The issue is not reproduced in solo but only on the modpack Ragnamod IV.

#### Expected behaviour:

____

#### Versions:

- This mod: 1.11.9 (Modpack [Ragnamod VI](https://www.curseforge.com/minecraft/modpacks/ragnamod-vi))
- Minecraft: 1.16.5
- Forge: Forge-36.2.0

#### Log file:

https://pastebin.com/vktXe85v

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like a performance issue (a tick took a very long time).
Can you share details about your network and if possible a profiler output?

**Comment by AerWyn81** [comment]
We are hosted on a dedicated server with 16Go RAM memory, 4 Core up to 5Ghz & 80Go storage and without network issue.
The server held the load for when 10 players were online yesterday. When it crashed 6x today, there were between 2/4 players.
I got another one crash, seem's a bit different : https://pastebin.com/kAMvuti1

EDIT : The last crash occurred when the player was not doing anything in his base.
Some other crash... 
https://pastebin.com/2FbRpLCW
https://pastebin.com/fLMij6Tj

EDIT 2 : It seems that by removing the IntegratedTunnels mod, crashes do not occur anymore. In the crash report, it talks about craft, maybe...

These lines appears in all crash reports: `org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorage....`

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/kAMvuti1">---- Minecraft Crash Report ----// Oh - I know what I did wrong!Time: 9/15 - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
This is probably a specific IT exporter that causes massive lag.

There's not much I can do with just the crashlogs and the system details.

I'll need some details about the ID/IT network this perf issue is caused by, or better: a profiler output.

**Comment by AerWyn81** [comment]
Hi

I have two test servers. The first one is without the IntegratedTunnels mod and works fine, no crashes. 
The second one is a backup of the complete modpack (with IntegratedTunnels because I suspect that it is he who can cause problems). 
I installed [Spark](https://www.curseforge.com/minecraft/mc-mods/spark) on the second one to try to give you a little more information. Note that the server starts and crashes after one minute without any player connected. I managed to make a spark profiler : https://spark.lucko.me/sQhgm7sP6Z

Hopefully this will help you

**Comment by rubensworks** [comment]
The profiling output doesn't seem to give much useful information unfortunately.

I suspect there's an IT network that connects to a massive storage range, which causes the performance issue.
There may be possibilities for optimization, but for that, I'd need to know exactly what that IT network looks like, and to what storage blocks it is connected.

**Comment by AerWyn81** [comment]
Hi, after several days of testing, it seems that this is a side effect of another issue on our modpack. A mob from a plugin riding a pig and make crash occur! Sorry for inconvenience

**Comment by rubensworks** [comment]
Good to hear the problem is resolved :-)
