### ISSUE TITLE
Capability crash 1.16.5

### ISSUE THREAD

**Issue by Darkere** [CyclopsMC/CyclopsCore#164]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm unsure if this bug is caused by the Screen itself or something in your code. From what I can tell the screen is just checking if the capability exists.

https://github.com/McJtyMods/RFToolsBase/blob/e08694a23e8a95eb0e064e6f5e7a63b9dac03ab1/src/main/java/mcjty/rftoolsbase/modules/informationscreen/blocks/InformationScreenTileEntity.java#L50

#### Steps to reproduce the problem:

1.  Not sure. I assume place a RFtools screen on a BlockEntity from ID

#### Expected behaviour:

____

#### Versions:

- This mod: CyclopsCore-1.16.5-1.11.9.jar    
- Forge: forge-1.16.5-36.2.4.jar

#### Log file:
https://gist.github.com/Darkere/6917f003a6265a24c68940321091c17f

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This error is thrown if the `Capability` reference is null: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.16/src/main/java/org/cyclops/cyclopscore/modcompat/capabilities/DefaultCapabilityProvider.java#L42

So it looks like `CapabilityInformationScreenInfo.INFORMATION_SCREEN_INFO_CAPABILITY` in RFTools is null, so there is probably something going wrong on their end. Could you report it to their issue tracker?

<blockquote><img src="https://opengraph.githubassets.com/6ab37992227dbad1b0a6b0b426315d60837d6c750f5eca39553c3a724c02723c/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsCore/DefaultCapabilityProvider.java at master-1.16 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/DefaultCapabilityProvider.java at master-1.16 · CyclopsMC/CyclopsCore</div></blockquote>
