### ISSUE TITLE
[1.18.1] npe crash on world join

### ISSUE THREAD

**Issue by Bass2style** [CyclopsMC/CyclopsCore#165]
#### Issue type:

- :bug: Bug 

____

#### Short description:

my modpack is crashing with a NPE when Cyclops Core and RFTools Utility are in the same pack, similar to #164 with RFTools Base.

#### Steps to reproduce the problem:

1. create a new world, and join it.
2. the modpack is crashing before you're in the world.

#### Expected behaviour:
joining the world without crashing. lul

____

#### Versions:

- This mod: 1.12.1 for MC 1.18.1
- Minecraft: 1.18.1
- Forge: 39.0.10
- RFtools Utility : 4.0.3

#### Log file:
my report on McJty's Github : https://github.com/McJtyMods/RFToolsUtility/issues/117
the logs provided in the report above : https://gist.github.com/Bass2style/5392ad11b9940966cb3a0460bd43f0f6
                                                          : https://gist.github.com/Bass2style/feed5388e99f6923fb08e20678fd3753

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like this was a problem in RFTools.

**Comment by Bass2style** [comment]
yes, McJty have fixed this yesterday, forgot to close the issue. thanks for your support.
