### ISSUE TITLE
Unneeded buckets being shown in JEI and the Creative inventory.

### ISSUE THREAD

**Issue by MagmaSlime123** [CyclopsMC/CyclopsCore#166]
#### Issue type:

- :bug: Bug 

____

#### Short description:

CyclopsCore putting Betweenlands liquids as default buckets into JEI and the Creative inventory.
CraftTweaker refuses to remove/hide them from JEI as well.

#### Steps to reproduce the problem:

Install Betweenlands, JEI, and this mod.
See JEI and the bottom part of the Misc. tab of the Creative inventory.

#### Expected behaviour:

The mod not putting Betweenlands liquids as default buckets into JEI and the Creative inventory.

#### Versions:

- This mod: 1.6.7.
- Minecraft: 1.12.2.
- Forge: 2860.

#### Log file:

N/A. I will provide it anyway.

[latest.log](https://github.com/CyclopsMC/CyclopsCore/files/8128707/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MagmaBro123** [comment]
No problem.

**Comment by MagmaSlime123** [comment]
No problem.

This may also occur with other mods that have liquids too, but I have not tested.

**Comment by rubensworks** [comment]
Why do you think this mod is causing the problem? This mod does not interact with JEI in any way.

**Comment by MagmaSlime123** [comment]
I have no idea. Without JEI they're only added to the Creative inventory, but no toggle/config exists for removing them.

**Comment by rubensworks** [comment]
Closing this issue then, sounds like a bug in Betweenlands.
