### ISSUE TITLE
[1.18.2] Failed to load Datapacks

### ISSUE THREAD

**Issue by Darkfiend009** [CyclopsMC/CyclopsCore#167]
#### Issue type:

- :bug: Bug 

____

#### Short description:

With the latest update to Cyclops Core (1.13.5), there is a datapack loading issue. I tested with only JEI and Evilcraft installed.

#### Steps to reproduce the problem:

1. Install Evilcraft/Cyclops Core
2. Create a new world
3. Failed to load datapacks error

#### Expected behaviour:

New world to generate

____

#### Versions:

- This mod: 1.13.5
- Minecraft: 1.18.2
- Forge: 40.1.0

#### Log file:

latest.log: https://pastebin.com/zHUmZpg8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Hmm, EvilCraft will require a minor fix for this.
