### ISSUE TITLE
Need Update for Forge 1.19-41.0.99

### ISSUE THREAD

**Issue by Arshia-D** [CyclopsMC/CyclopsCore#170]
Game Crash mod need update for new forge version 
- Minecraft: 1.19
- Forge: 41.0.99

**Comment by rubensworks** [comment]
Yes, I'm aware.

**Comment by rubensworks** [comment]
@DJ1Silva Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
