### ISSUE TITLE
CyclopsCore preventing mobs from getting xray attribute from 

### ISSUE THREAD

**Issue by Saereth** [CyclopsMC/CyclopsCore#172]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I opened an issue because of a server and singleplayer crash relateed to enhanced AI and the dev pointed the issue back here to cycloscore preventing some mobs from getting the xray attribe which is then causing the game to crash.

#### Steps to reproduce the problem:

1. run a pack with evilcraft/cyclopsCore/EnhancedAI and randomly you will get crashes

#### Expected behaviour:

The mobs should get assigned the xray attribute and not crash
____

#### Versions:

- This mod: CyclopsCore-1.18.2-1.16.0
- Minecraft: 1.18.2
- Forge: 40.1.73
- Evilcraft: EvilCraft-1.18.2-1.2.5
- 

#### Log file:
https://pste.me/v1/paste/jwruXYXu25Y/raw

Here is a link to the original issue 
https://github.com/Insane96/EnhancedAI/issues/51

**Comment by rubensworks** [comment]
Thanks for reporting!
