### ISSUE TITLE
1.19.1 support

### ISSUE THREAD

**Issue by a-sakharov** [CyclopsMC/CyclopsCore#173]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Hello.
Curseforge provides builds for 1.19 and 1.19.2, but both of them looks to bu incompatible with 1.19.1. Can you also provide support for 1.19.1?
Thanks.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
No sorry, 1.19 and 1.19.1 won't be maintained anymore. Just update to 1.19.2 :-)
