### ISSUE TITLE
Causing server to freeze for a few minutes or/and time  everyone out and make server unresponsive.

### ISSUE THREAD

**Issue by jaynotgay** [CyclopsMC/CyclopsCore#175]
Forge CyclopsCore-1.19.2-1.18.2 ATM8
![image](https://user-images.githubusercontent.com/30220126/227713008-dac60520-e532-4cc4-9426-59403a12d6dd.png)
Causing server to freeze for a few minutes or/and time  everyone out and make server unresponsive.
Here is a link to some other mods that may be causing this to happen https://github.com/AllTheMods/ATM-8/issues/1135

**Comment by rubensworks** [comment]
@jaynotgay Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
