### ISSUE TITLE
1.20.1 - Forge 43.1.3 Client Crash on Startup with ``java.lang.ClassNotFoundException: org.cyclops.cyclopscore.datastructure.DimPos``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/CyclopsCore#179]
#### Issue type:

- :bug:

____

#### Short description:

Client Crashes with ``CyclopsCore-1.20.1-1.18.13.jar`` this however does not crash on server so at first it was confusing.

#### Steps to reproduce the problem:

Use version ``CyclopsCore-1.20.1-1.18.13.jar``

#### Expected behaviour:

No crash.

____

#### Versions:

- This mod: CyclopsCore-1.20.1-1.18.13.jar
- Minecraft: 1.20.1
- Forge: 43.1.3

Don't have time to test plus it works fine on version ``CyclopsCore-1.20.1-1.18.11.jar``

#### Log file:

https://gist.github.com/P3rf3ctXZer0/047d461487af1e5b3b8b72f1b9714ddb

**Comment by rubensworks** [comment]
I suspect your jar file is corrupt somehow.
Can you try re-downloading?

**Comment by P3rf3ctXZer0** [comment]
I tried 3 times ... its the same each time just going back a version fixes it. Is upload bad? Curse has been having server issues again in the last week.

**Comment by rubensworks** [comment]
Can you try this one? https://github.com/CyclopsMC/packages/packages/769892 (`cyclopscore-1.20.1-1.18.13-389.jar` at the bottom)

<blockquote><img src="https://opengraph.githubassets.com/dfa9b9a24ee44ae983740d0c950ffc3fafdf20b6886a33fb38e15a3d450331f1/CyclopsMC/packages" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/packages">Package org.cyclops.cyclopscore.cyclopscore · CyclopsMC/packages</a></strong></div><div>Maven repo for CyclopsMC mods. Contribute to CyclopsMC/packages development by creating an account on GitHub.</div></blockquote>

**Comment by P3rf3ctXZer0** [comment]
Yes I can.

**Comment by P3rf3ctXZer0** [comment]
It seems to work.
