### ISSUE TITLE
`dumpregistries` subcommand is not guarded by a permission

### ISSUE THREAD

**Issue by andriihorpenko** [CyclopsMC/CyclopsCore#180]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The `dumpregistries` subcommand has no permission requirement set, giving anyone an ability to execute this command. Even though this is not a vulnerability, this _may_ cause unnecessary load on a server when used dozens of times by bad actors.

#### Steps to reproduce the problem:

1. Be a player with no advanced permissions granted
2. Use `/cyclopscore dumpregistries`

#### Expected behaviour:

Guard a command with an OP check or permission level >= 2, like vanilla does in dozens of commands.

____

#### Versions:

- This mod: 1.19.1
- Minecraft: 1.19.2
- Forge: 43.3.13

#### Log file:

No log file required

**Comment by rubensworks** [comment]
Thanks for reporting!
