### ISSUE TITLE
Failure to load Cyclops Core for Integrated Dynamics and associated addons.

### ISSUE THREAD

**Issue by WarMind666** [CyclopsMC/CyclopsCore#184]
#### Issue type:

- :bug: Bug 

____

#### Short description:

NoClassDefFound error when trying to load CyclopsCore, causing cascading failure through Integrated Dynamics mods and addons.

#### Steps to reproduce the problem:

1. Add CyclopsCore, CommonCapabilities, IntegratedDynamics to a pack with over 167 mods.
2. Launch the pack.
3. Issue appears.

#### Expected behaviour:

Expected the mod to load properly, and launch Minecraft.
____

#### Versions:

- This mod: 1.19.1
- Minecraft: 1.20.4
- Forge: Neoforge 20.4.237

This is a custom modpack that I have created, and if I go above 167 other mods active, and it does not matter what mod I activate, The pack has about 200 mods installed total, CyclopsCore will not initialize properly, which cascades into failing every other ID mod, and CommonCapabilities.  Tried this with only CyclopsCore, CommonCapabilities, and Integrated Dynamics installed and active.  Once I go over 167 mods active in the pack, library mods included, It crashes again with the same errors.

#### Log file:

https://pastebin.com/1srUUyQZ

#### Crash log:

https://pastebin.com/7xNx7Gz9

**Comment by rubensworks** [comment]
Thanks for reporting!
