### ISSUE TITLE
Crash on NeoForge 21.0.65

### ISSUE THREAD

**Issue by Nekkusu3** [CyclopsMC/CyclopsCore#185]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Starting Minecraft throws an error. Seems the Cyclops API has some sort of issue.
`[17Jul2024 22:05:21.527] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: evilcraftcompat, class org.cyclops.evilcraftcompat.EvilCraftCompat
java.lang.NoClassDefFoundError: org/cyclops/commoncapabilities/api/capability/work/IWorker`

I recommend adding the NeoForge Version that was used/tested on future releases. Theres a new version every few days as it is in beta.

#### Steps to reproduce the problem:

Fresh NeoForge Installation
Move Evilcraft / Cyclops .jar to the mods directory
Game doesnt start

____

#### Versions:

client-1.21-20240613.152323-srg.jar
EvilCraft-1.21-neoforge-1.2.39.jar 
CyclopsCore-1.21-neoforge-1.19.2.jar & CyclopsCore-1.21-neoforge-1.19.1.jar
neoforge-21.0.65-beta-universal.jar

#### Log file:
[latest.log](https://github.com/user-attachments/files/16274169/latest.log)
[crash-2024-07-17_22.05.23-fml.txt](https://github.com/user-attachments/files/16274225/crash-2024-07-17_22.05.23-fml.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
In the meantime, installing CommonCapabilities should fix your issue.
