### ISSUE TITLE
[1.21.1-Neo] Instant disconnect upon trying to join server. (org.cyclops.cyclopscore.helper.RecipeSerializerHelpers.writeItemStackOrItemStackIngredientChance(RecipeSerializerHelpers)

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/CyclopsCore#191]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Instant disconnect when joining server all of a sudden. Logs point to CyclopsCore so I'll report here see what comes of it.
![ss1](https://github.com/user-attachments/assets/a677c95d-5c3e-49ed-bd91-654772c9dae9)

#### Steps to reproduce the problem:

1. Attempt to join server.
2. Instant disconnect.

![ss](https://github.com/user-attachments/assets/3e6276e9-96dd-4d57-affb-917f2d0ff684)

#### Expected behaviour:
That server is joinable without disconnect.

____

#### Versions:

- This mod: 1.23.0-601
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.54

#### Log file:
https://gist.githubusercontent.com/Gbergz/1e59c6e65ace4b9b30c973c1085602c5/raw/de3dd3f649ef53a9d46c205d6581f76a325f1dfa/gistfile1.txt

### EDIT:

After some digging I found out that removing Integrated Dynamics causes this issue to disappear. And re-adding it makes issue appear again. So something around Integrated Dynamics.

Versions for integrated mods:
IntegratedDynamics v1.23.5
IntegratedCrafting v1.1.10
IntegratedTerminals v1.5.2
IntegratedTunnels v1.8.28

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: use ItemStack codecs that accept empty in read and write: https://github.com/CyclopsMC/CyclopsCore/blob/master-1.21/loader-neoforge/src/main/java/org/cyclops/cyclopscore/recipe/ItemStackFromIngredient.java#L79-L100

Just weird that this hasn't happened before. Probably indicates broken/custom recipes in a modpack.

<blockquote><img src="https://opengraph.githubassets.com/d914cfacc8e9bd7ea82f03001fb6fdfe2764ff740781d2fb68c3a25dc445876d/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore/blob/master-1.21/loader-neoforge/src/main/java/org/cyclops/cyclopscore/recipe/ItemStackFromIngredient.java">CyclopsCore/loader-neoforge/src/main/java/org/cyclops/cyclopscore/recipe/ItemStackFromIngredient.java at master-1.21 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by rubensworks** [comment]
I'll push a fix which should fix your problem, but there's a small chance it may not (since I wasn't able to reproduce the problem).
Once you've updated to the new version, and the problem should still occur for you, please let me know.

**Comment by Gbergz** [comment]
Tried just now and unfortunately the issue persists on v1.23.6.
Here's the servers latest.log again:
File: [latest.log](https://github.com/user-attachments/files/17100692/latest.log)
Or link: https://gist.githubusercontent.com/Gbergz/4aeecfe6f16992d7456ffb8ed9e95d82/raw/91b3f51b59b87307f4304eb04aec66529b6b2afb/gistfile1.txt

**Comment by rubensworks** [comment]
Can you reproduce the problem without any other mods installed? I'm suspecting some other mod in your pack may be breaking vanilla ingredient seralization.

**Comment by Gbergz** [comment]
No I can't so I suspect this is another mod causing issues with Integrated Dynamics/Cyclops Core.. hmm annoying.. :s
Not sure how to find out which other than removing mods one by one until it works, but that's gonna take a long time with so many mods.

**Comment by rubensworks** [comment]
You could try binary search, which should be a lot faster than removing one-by-one: iteratively removing half of the mods until you find the offending one.

**Comment by Gbergz** [comment]
Yep, was going to do that and I have done it now.

Removing Occultism makes the issue go away and world is now joinable again. Re-adding it makes issue reappear.

**Comment by Gbergz** [comment]
After further testings, readding Occultism and removing KubeJS also solves it, so it might be something there.
Edit: Re-adding KubeJS and then deleting the KubeJS folder with the scripts also solves it, so might be something with my scripts currently.

Just weird that this started recently.

**Comment by Gbergz** [comment]
Found the issue, it was a KubeJS item ban script I have that is breaking stuff together with Cyclops Core + Integrated Dynamics I guess..

Removing it fixes this issue.

**Comment by rubensworks** [comment]
Glad to hear you found the problem!

**Comment by Gbergz** [comment]
Thanks for the help on the way, appreciated. :)
