### ISSUE TITLE
Cyclopscore crash when launching the game (1.20.1 / Forge 47.3.0)

### ISSUE THREAD

**Issue by Snow123159** [CyclopsMC/CyclopsCore#192]
#### Issue type:

- :bug: Bug 

____

#### Short description:

This mod is required to play with Evil Craft mod but it crashes the game when launched, preventing its use and the use of other mods.

#### Steps to reproduce the problem: 

1. Install the latest version of Cyclopscore for 1.20.1 minecraft version.
2. Launch the game
3. The game crashed

#### Expected behaviour: Just playing with Evil Craft mod.

____

#### Versions:

- This mod: Personnal modpack / Sigleplayer mode
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I'm assuming there's another mod in your pack that is breaking things.
Could you try to identify the offending mod, and report this to their issue tracker?
Happy to make changes on my end if this would be needed.
