### ISSUE TITLE
Crash on destroy block

### ISSUE THREAD

**Issue by LotuxPunk** [CyclopsMC/CyclopsCore#21]
Hello, can you help me please ?

[http://pastebin.com/3CChxKqC](url)
[crash-2016-08-22_13.40.04-server.txt](https://github.com/CyclopsMC/CyclopsCore/files/431143/crash-2016-08-22_13.40.04-server.txt)

**Comment by rubensworks** [comment]
This is an Integrated Dynamics crash, and has been fixed in CyclopsMC/IntegratedDynamics@731fa2dedc1fc14694023d4fc393421f07670a81, but has not been released (yet).
