### ISSUE TITLE
Crash with Pressure Pipes after ID/CC/CC update

### ISSUE THREAD

**Issue by utoc** [CyclopsMC/CyclopsCore#25]
Greetings!

Crash here: http://pastebin.com/KZS0GiDf

This crash happened after updating CyclopsCore, CommonCapab and ID to 0.8.0, 1.2.0 and 0.6.0 Respectively.  FML 2095 on MC1.10.2 with bdlib 1.12.2.14 and pressurepipes 1.3.1.16

I don't know what the setup was that crashed it; it happened on a live server with several users bases' being loaded at server start.  In the meantime we've reverted and the issue has been abated.

**Comment by rubensworks** [comment]
That looks like a Forge block mapping issue, I thought those were a thing from the past...
Does the crash re-occur after a restart?

**Comment by utoc** [comment]
Every time, unfortunately.

**Comment by rubensworks** [comment]
Fixed in Integrated Dynamics, CyclopsMC/IntegratedDynamics@155f237a8146ee5ebcc3dd01b07e8cfc68e1210e
Scheduled for next release.
