### ISSUE TITLE
Random Server crash on Start-Up

### ISSUE THREAD

**Issue by lilmoefow** [CyclopsMC/CyclopsCore#26]
This does not happen everytime, and I am not even necessarily sure it is caused by Cyclops Core (its just the first mod referenced in the crash)

http://pastebin.com/7y9H9PDk

If you happen to know why its happening or can point me in the right direction of whats causing it, just let me know.

**Comment by rubensworks** [comment]
I'm not really sure what could cause a crash like this, might be something funky in your JVM. If anyone else is experiencing this crash, please let me know.

**Comment by UnNinja** [comment]
WE've recently begun experiencing this crash as well. Doesn;t happen every boot up. http://pastebin.com/8fJRpR7e

**Comment by rubensworks** [comment]
@UnNinja This seems to be a completely different crash, could you create a separate issue for it? Thanks.

**Comment by rubensworks** [comment]
I'm not able to reproduce this with any of the Cyclops mods loaded on the lastest Forge version.
I suspect that you are using a mod that is somehow messing with class loading, which could result in such strange crashes.
It is very likely that such a crash will also occur in other mods when this mod is not loaded.

I suggest that you have a look at the mods you are using, and try removing them one by one to see which one causes the problem.

**Comment by lilmoefow** [comment]
I feel like it was an issue with minetweaker.  Can probably just close this for now.  I was just recently able to update CraftTweaker and Modtweaker, and have not had any of those crashes since.  Using Sponge on the server I need to stay on the same forge versions they use, so I sometimes behind a version or 2 on some mods.  

Sorry for the bother
