### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by UnNinja** [CyclopsMC/CyclopsCore#27]
http://pastebin.com/4FMP1jPF
Doesn't happen every time. maybe about 1 in 4 times

**Comment by rubensworks** [comment]
I'm not able to reproduce this with any of the Cyclops mods loaded on the lastest Forge version.
I suspect that you are using a mod that is somehow messing with class loading, which could result in such strange crashes.
It is very likely that such a crash will also occur in other mods when this mod is not loaded.

I suggest that you have a look at the mods you are using, and try removing them one by one to see which one causes the problem.

**Comment by rubensworks** [comment]
Closing this because of non-reproducibility.
