### ISSUE TITLE
IC2Classic Crash

### ISSUE THREAD

**Issue by Speiger** [CyclopsMC/CyclopsCore#28]
Since 1.10.2 IC2Classic has his own File Structure and is not compatible with IC2Exp Core class access anymore.

This crash comes from one of your mods. I tried to find out which directly but i was unable to find which mod has the classes...

Here is the crash:
http://pastebin.com/nwSF6Tbp

IC2Classic has a second modID where you can detect when it is loaded.
"IC2-Spmod-Classic"
Would be nice if you take care of that.
If you need any help ask.

**Comment by rubensworks** [comment]
> Since 1.10.2 IC2Classic has his own File Structure and is not compatible with IC2Exp Core class access anymore.

Why are you still using the same main mod id then? I don't think it's a good idea to share modid's with different mods.

Eitherway, it's an easy thing for me to fix in CommonCapabilities, but still, I think you should reconsider your mod id.

**Comment by Speiger** [comment]
Well mainly because of modcompat because even so if ic2c is not ic2exp its still ic2 so using that modid makes actually sense because i support their API sich close systems...

What you could do is a custom sidedProxy which would be the best solution or prevent the load of your ic2 plugin when you detect ic2classic. That's why I have two modids
