### ISSUE TITLE
Optifine Crash

### ISSUE THREAD

**Issue by A-Vladimir** [CyclopsMC/CyclopsCore#36]
Crashes when on launch when i have Optifine installed using CyclopsCore-1.9.4-0.9.0 and OptiFine_1.10.2_HD_U_D4, CyclopsCore-1.9.4-0.8.2 didn't crash with it and can't downgrade to it because i am playing Skyfactory 3 on server.

**Comment by rubensworks** [comment]
I can't do anything without a crash report.
Your best bet is to report this on the Optifine issue tracker, my focus is on supporting regular Forge-based environments, Optifine always does some funky stuff.

**Comment by A-Vladimir** [comment]
[crash-2017-01-09_05.06.52-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/694846/crash-2017-01-09_05.06.52-client.txt)

I know it says "Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.0-anarchy.jar)" but i tried removing it and it still crashes.

ps: I have tried to find the optifine issue tracker but their site shows no sign of it.

**Comment by nderuijter** [comment]
It seem I have the same issue.

Modpack: FTBPresentsSkyFactory3-3.0.4-1.10.2 (BETA)
which contains CyclopsCore-1.9.4-0.9.0
OptiFine_1.10.2_HD_U_D4 added.

No issue when Optifine is not loaded.

Crash Log:
http://pastebin.com/v65DUnAj

**Comment by sp614x** [comment]
Looks like one of the core mods is incorectly patching the TextureAtlasSprite class.
There is a warning about FoamFixAPI, it may be the problem.
To isolate the problematic mod the crash has to be reproduced with only one core mod installed.

**Comment by LovelyFlare** [comment]
Actually caused by Brandon's Core.

**Comment by A-Vladimir** [comment]
FoamFixAPI, is not the problem you get the same crash report without it.

**Comment by JohnMFSteel** [comment]
yeah this crash is definitely caused by cyclopes core and I hope a fix comes soon cause I love using optifine

**Comment by rubensworks** [comment]
@Johnvista64 It's likely to be one of the coremods you're using. Try adding _only_ CyclopsCore and Optifine to an environment and let me know if it still crashes.

**Comment by toaran** [comment]
@rubensworks 
i had the same issue
i testet only CyclopsCore  with Optifine and it works fine... i will try the other core mods from SF3 now...

**Comment by toaran** [comment]
hmpf it was the last coremod i tried... Surge
with only surge and optifine  as mods it also crashes...

disable Surge and SF3 loads...

**Comment by rubensworks** [comment]
@toaran Could you report that to the Surge issue tracker and link to that issue from here?
Thanks for testing this.

**Comment by toaran** [comment]
someone else already had the same issue

https://github.com/Epoxide-Software/Surge/issues/9

**Comment by JohnMFSteel** [comment]
@rubensworks just had to go and make this complicated couldnt take the blame I have firmly ruled out all mods that errored during the crash... which makes this issue all the more complicated. That said @rubensworks is off the hook as the person that has an issue to fix. As for why your mod gave off the exception on the crash I do not know, if you could shine some light on that. That would be great. :\ the modpack in question is still FTBPresentsSkyFactory3-3.0.4-1.10.2 (BETA)

**Comment by rubensworks** [comment]
@Johnvista64 The reason why I think it crashes when loading CyclopsCore is because CyclopsCore appears to be the first mod loading the `TextureAtlasSprite` class, which has apparently been corrupted by the combination of Surge and Optifine.
