### ISSUE TITLE
Integrated Dynamics - Squeezer Crash

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [CyclopsMC/CyclopsCore#37]
http://pastebin.com/DQjbLxPM

Running SpongeForge 
CyclopsCore Version: 1.9.4-0.0.1
Integrated Dynamics: 1.10.2-0.6.5

Thanks

**Comment by rubensworks** [comment]
Your CyclopsCore version seems to be invalid, please provide the correct version, and make sure you are using the latest version.

**Comment by Rob5Underscores-zz** [comment]
Whoops. Not sure what I was reading: CyclopsCore- 1.9.4-0.8.2

**Comment by rubensworks** [comment]
In that case you are not using the latest CyclopsCore version, which is 0.9.0.
That version fixes #33, which looks like the same problem as you are reporting here.

**Comment by Rob5Underscores-zz** [comment]
Do you forsee any issues compiling 0.9.0 as 0.8.2 (such that players on my server can still join)

**Comment by rubensworks** [comment]
It shouldn't be a problem, but I strongly advise you to just let the clients update as well, to avoid any other weird problems.
