### ISSUE TITLE
Issue - Crash [1.10.2] - Forge 202 - Clientside while on server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/CyclopsCore#38]
I clicked the end key on keyboard. It ended my client.

Crashlog
https://gist.github.com/P3rf3ctXZer0/9d3bbf5c7534ea0d147e52fb86686d6e

Fulllog
https://gist.github.com/P3rf3ctXZer0/cd2d9a6a9d270b30322fdcc1aef38a43

**Comment by rubensworks** [comment]
When did you press the end key? When you were in a gui? Or when in the world?

**Comment by rubensworks** [comment]
Closing this in favor of #36
