### ISSUE TITLE
1.11.2-0.9.1 crashes client on startup

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/CyclopsCore#41]
http://pastebin.com/AHuKacFE

**Comment by rubensworks** [comment]
@kreezxil This seems to be caused by the following error: `Caused by: java.io.FileNotFoundException: G:\Documents\Curse\Minecraft\Instances\morpheus!! (The system cannot find the file specified)`.
Perhaps the `!!` in your instance name is causing the issue?
