### ISSUE TITLE
CyclopsCore causing lag with RFTools crafter

### ISSUE THREAD

**Issue by Time6628** [CyclopsMC/CyclopsCore#42]
Not quite sure what it is, but this occurs a lot with RFTools crafters(Tier 3s mostly).

Here's a warmroast of the problem:
![alt-text](http://i.imgur.com/nS4IMbv.png "WarmRoast")

Not quite sure what you guys everytime an item stack loads, but it is causing quite a problem.

ModPack: Sky Factory 3

**Comment by rubensworks** [comment]
What version of CyclopsCore and CommonCapabilities are you using? Because this should be fixed in the latest versions.

**Comment by Time6628** [comment]
CyclopsCore-1.9.4-0.9.0-469
CommonCapabilities-1.9.4-1.2.2

**Comment by rubensworks** [comment]
Yep, those are not the latest versions. Either wait for SF3 to update, or update it yourself.
