### ISSUE TITLE
[1.10.2] Crash after updating on CyclopsCore-1.9.4-0.10.0

### ISSUE THREAD

**Issue by Tahakk** [CyclopsMC/CyclopsCore#44]
Hi there,
I have a small server for few players and I'm trying to keep all mods weekly updated. 
Lately after every update I was getting crash while starting up a client. Figured out it is happening when I update CyclopsCore-1.9.4-0.9.3 to CyclopsCore-1.9.4-0.10.0. Same thing happening on server.

Function version at:
**CyclopsCore-1.9.4-0.9.3**
**forge-12.18.3.2254**

Stops working at:
**CyclopsCore-1.9.4-0.10.0**
**forge-12.18.3.2254**

[fml-client-latest.txt](https://github.com/CyclopsMC/CyclopsCore/files/890939/fml-client-latest.txt)
[fml-server-latest.txt](https://github.com/CyclopsMC/CyclopsCore/files/890940/fml-server-latest.txt)

Modpack is SF3 3.0.6 with bit of modifying.

Any help will be appreciated.

**Comment by rubensworks** [comment]
It seems highly unlikely that CC is causing this, the crash seems to be caused by something related to achievements.
Did you update any other mods? Perhaps a achievements-related mod is causing the crash.

**Comment by Tahakk** [comment]
I updated everything that Curse (Twitch Client) offered me up to this date.

**Comment by rubensworks** [comment]
@Tahakk Well yes, that might include other mods as well.
I highly doubt it is caused by CC, but if you can reproduce it by _only_ updating this mod, let me know here.

**Comment by Tahakk** [comment]
I updated my mods repository that I'm keeping for easy update for other players.

[GitHub Repo](https://github.com/SimonSkapik/mods/)

You can try it yourself. 

Thanks for your help.
