### ISSUE TITLE
Message during loading

### ISSUE THREAD

**Issue by NielsPilgaard** [CyclopsMC/CyclopsCore#50]
Hey! :)

Every time I launch my server, I get the same message from CyclopsCore, saying my config file is old, and should be deleted in order to regenerate - I've now done that a few times, so the message seems persistent.

**Comment by rubensworks** [comment]
Do you mean that you are getting the warning every time after deleting the config file, _while_ using the same CyclopsCore version?

**Comment by NielsPilgaard** [comment]
Yep, exactly, forgot to mention that ^^' Thanks!
