### ISSUE TITLE
1.12-0.10.6 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/CyclopsCore#54]
Notes:
     on startup

crash report:
https://gist.github.com/6ed7c15d9becc2b8fc86c174d736d7c8

fml server latest:
https://gist.github.com/0ab5e8d877f6ab3b85ed9b8190b32d01

possibly related: #53

**Comment by rubensworks** [comment]
Yes, indeed duplicate of #53
