### ISSUE TITLE
(1.12) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [CyclopsMC/CyclopsCore#57]
Hi ! My modpack crash with your mod and some other mods (i'm going to advert other mods authors)
[crash-2017-07-17_11.03.47-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/1152048/crash-2017-07-17_11.03.47-client.txt)
Thank you !

**Comment by rubensworks** [comment]
Duplicate of #56
