### ISSUE TITLE
Crash with 1.11.2 Equal objects must have equal hashcodes

### ISSUE THREAD

**Issue by cursinorock** [CyclopsMC/CyclopsCore#58]
Crash on custom modpack.
last version of forge *.2425
[crash-2017-07-27_02.15.40-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/1179097/crash-2017-07-27_02.15.40-client.txt)

**Comment by rubensworks** [comment]
This seems to be related to the DarkOre pulverizer registration from EvilCraft: https://github.com/CyclopsMC/EvilCraft-Compat/blob/master-1.11/src/main/java/org/cyclops/evilcraftcompat/modcompat/thermalexpansion/ThermalExpansionModCompat.java#L63
But as far as I can see, there should be no reason why EC's DarkOre block hashcode should change over time.
@cursinorock Can you report this to the Thermal Expansion issue tracker as well and link back to this issue?

**Comment by Tahakk** [comment]
https://github.com/CoFH/Feedback/issues/428

**Comment by rubensworks** [comment]
@cursinorock Just tried loading up EvilCraft and Thermal Expansion (+ lib mods) and I couldn't reproduce this issue.
So another mod must be causing this, possibly by registering to the oredict in the PostInit phase.

You can try removing mods until it doesn't crash for detecting the cause.
