### ISSUE TITLE
Inconsistency in indexed inventories

### ISSUE THREAD

**Issue by lmartos** [CyclopsMC/CyclopsCore#60]
Hello, we're playing with the 1.12 version of this mod and every time someone moves an item between an inventory, be it a chest, an ME system or any other inventory this specific error pops up in the server console and laggs out the server momentarily.

[Cyclops Core]: Indexed inventory at inconsistent with last empty 728 and last non-empty 728.

**Comment by rubensworks** [comment]
That warning is only thrown when something goes wrong inside a Colossal Chest, which must be a bug indeed. Nothing else happens other than printing the warning, as can be seen here: https://github.com/CyclopsMC/CyclopsCore/blob/cbb8b80909a33a60e257f1a4c9951d92d53ce8cc/src/main/java/org/cyclops/cyclopscore/inventory/IndexedInventory.java#L162-L165
So this is unlikely to be the cause of your lag.

**Comment by rubensworks** [comment]
Note to self: write some unit tests in `IndexedInventory` to see what may be going wrong.
