### ISSUE TITLE
FYI/1.12 15 update required nag

### ISSUE THREAD

**Issue by Nexusdog** [CyclopsMC/CyclopsCore#62]
This is the nag message I get in MC even though CC is up to date

https://i.gyazo.com/bff43f7122c74e875b33ce2933899d3f.png

Obviously its not affecting the game afaik, but thought you'd want the heads up.

**Comment by rubensworks** [comment]
Yeah, I should update the version tracker.
(The curseforge API was down last time I tried to do it...)

**Comment by rubensworks** [comment]
Done https://github.com/CyclopsMC/Versions/commit/4e8c4d465b8b0e62f6ad427f190667003c948244
