### ISSUE TITLE
[1.12] - CyclopsCore-1.12-0.10.16 missing on Curseforge

### ISSUE THREAD

**Issue by Protheus** [CyclopsMC/CyclopsCore#63]
![image](https://user-images.githubusercontent.com/1455178/29981690-fbc6afee-8f4e-11e7-8e25-afb89ef104f2.png)

There is no **CyclopsCore-1.12-0.10.16.jar**  on Curseforge

![image](https://user-images.githubusercontent.com/1455178/29981715-17548ec0-8f4f-11e7-978a-5175a3636173.png)

**Comment by rubensworks** [comment]
It's on CF, just awaiting approval (for two hours already). Let's hope they approve it soon...

**Comment by Protheus** [comment]
Cool
