### ISSUE TITLE
Make breaking changes to the type system

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CyclopsCore#68]
There's a lot of work (#67 and some stuff I haven't written yet) that needs to be done to the type system, but is a breaking change for any mod that uses this one. Once Forge for 1.13 comes out, we should make these changes since 1.13 is going to break everything anyway.

**Comment by rubensworks** [comment]
This should be mostly resolved in the 1.14 branch: https://github.com/CyclopsMC/CyclopsCore/tree/master-1.14

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>
