### ISSUE TITLE
Ctd on world load

### ISSUE THREAD

**Issue by sefldron** [CyclopsMC/CyclopsCore#76]
I'm not 100% sure but the newest versions of core crash for me. I'm doing some testing with disabling the update process right now and re running it. Loaded fine yesterday when I updated to 1.12.2 but I was online then.
   Calling a ticking error. I will pastebin the issue to you in a bit if nothing fixes it.

**Comment by sefldron** [comment]
It is version checking i believe.
Forge versioning comparable version parser
To default artifact version
To org.cyclops.'core.init.modbaseversionable.needs update
To '.'.tracking.versions.ontick
Then a bunch of fml and Minecraft references to entities and such.
If you want to see let me know.
   Only happens when offline. Never did with 0.10.17 and back though.

**Comment by rubensworks** [comment]
Please send me the crashlog, not much I can do without it.

**Comment by sefldron** [comment]
Ok cool give me a few minutes to put it up.

**Comment by sefldron** [comment]
https://pastebin.com/gRFZ27LD
  if you want me to i will do another run online to see if it loads correctly now that I am on my pc
i will also do a run offline without foamfix anarchy and use the lawful version or even without.
just let me know how i can help

**Comment by rubensworks** [comment]
Thanks! Will be fixed in next update.
