### ISSUE TITLE
Crash with CoFH Mods.

### ISSUE THREAD

**Issue by Y0ungSandwich** [CyclopsMC/CyclopsCore#80]
I am getting this crash with Thermal Dynamics:
https://pastebin.com/VZaq1ujB

All mods involved are latest versions. 
CyclopsCore-1.12-0.10.20
IntegratedDynamics-1.12-0.9.2

Not sure if this is more Cyclops mods or CoFH.

**Comment by rubensworks** [comment]
It looks like TD iterates over items _before_ capabilities have been registered.
This is not a mistake by them, just something I haven't taken into account, will look into it, thanks for reporting.

**Comment by Y0ungSandwich** [comment]
Great thank you for your time!  Always glad to help.
