### ISSUE TITLE
MC reporting CyclopsCore-1.12.2-0.10.22.jar being available as a 1.12 file

### ISSUE THREAD

**Issue by Nexusdog** [CyclopsMC/CyclopsCore#84]
As title

**Comment by rubensworks** [comment]
Please clarify, I don't know what the problem is.

**Comment by Nexusdog** [comment]
The mod update notification jobbie, with the flashing emerald icon, that fella.

![](https://i.gyazo.com/11fccc56eff71d9cf987ed8a40383f49.png)
](url)

**Comment by rubensworks** [comment]
That's intended. Our update tracker is scoped by minor MC version (1.12.x). You can either update, ignore it, or disable our version checker in the config.
