### ISSUE TITLE
Netty leak fix posted

### ISSUE THREAD

**Issue by trogarus** [CyclopsMC/CyclopsCore#85]
I am sorry to say, but I don't think you've totally managed this in the latest update. I can sit with game open and task manager and still see memory continually creep up little by little. The only thing I have cyclic in the world are miners, 4 of them.

**Comment by trogarus** [comment]
Confirmed. Removed 6 cyclic miners (forgot about the two at spawn) used to mine futurepack crystals and memory creep is gone. Sorry, but doesn't seem you have the leak quite completely fixed. Crystals are still growing on the sand, so it's not the crystals or the futurepack sand.

**Comment by rubensworks** [comment]
What does cyclic miners have to do with this mod?

**Comment by trogarus** [comment]
It's a core mod for Cyclic?

**Comment by StaticPH** [comment]
It shouldn't be though? At least not according to curseforge

**Comment by rubensworks** [comment]
@trogarus No.
