### ISSUE TITLE
Crash breaking Integrated Dynamics battery

### ISSUE THREAD

**Issue by ZephaniahNoah** [CyclopsMC/CyclopsCore#86]
I don't know where I should report this but it says CyclopsTileEntity in the crash report. I connected an Energy Battery to some CoFH leadstone flux duct, realized that they can't pull energy from it, and broke it. The game immediately crashed.
[crash-2017-11-01_13.43.55-client.txt](https://github.com/CyclopsMC/CyclopsCore/files/1435737/crash-2017-11-01_13.43.55-client.txt)
Also I have a question if anyone could answer... Why can't I pull RF from Energy Batteries? I've tried various types of RF cable from different mods. None work.

**Comment by rubensworks** [comment]
Ah, that rendering bug before blocks are loaded again...

You *should* be able to pull from batteries though. Which ones specifically do not work?

**Comment by ZephaniahNoah** [comment]
I tried both Hardened and Leadstone Fluxducts as well as Basic Universal Cable from Mekanism.

**Comment by DeadSix27** [comment]
@rubensworks Same issue when setting stuff to "0"(air) with world edit:
https://gist.github.com/DeadSix27/53a1d18dae6a695d3ec68de6dd1da637

**Comment by rubensworks** [comment]
Fixed in https://github.com/CyclopsMC/IntegratedDynamics/commit/76fd28817fe09b2731744c104caac085e6be42c4
