### ISSUE TITLE
Crash on get fluid icons? for 1.10.2

### ISSUE THREAD

**Issue by Divineaspect** [CyclopsMC/CyclopsCore#90]
https://pastebin.com/KbEZVrEa

**Comment by rubensworks** [comment]
Somehow, you have inserted a `null` Fluid inside a FluidStack (inside the chalice). Any idea how this might have happened?

**Comment by Divineaspect** [comment]
not sure, we're presently using them to transport evilcraft blood and ender io liquid xp
