### ISSUE TITLE
switch Map Pair to Table 

### ISSUE THREAD

**Issue by loordgek** [CyclopsMC/CyclopsCore#95]
https://github.com/loordgek/CyclopsCore/commit/b6ab7a0fb40dc548d98032e0568ee9917c2df36a

it just looks cleaner 
i dont know what the performance of it is did not test it
feel free to take it

**Comment by josephcsible** [comment]
If you want us to pull that change, please submit an actual pull request instead of just linking a commit from an issue.

**Comment by loordgek** [comment]
will do

**Comment by rubensworks** [comment]
Sure, why not. Feel free to send a PR as @josephcsible has said.

**Comment by loordgek** [comment]
https://github.com/CyclopsMC/CyclopsCore/pull/98
 closing this
